import ROOT

class Quantity(object):
  def __init__(self, name_nano='', name_flat='', title='', label='', nbins=0, bin_min=0., bin_max=0.):
    self.name_nano = name_nano
    self.name_flat = name_flat
    self.title = title
    self.label = label
    self.nbins = nbins
    self.bin_min = bin_min
    self.bin_max = bin_max


quantities_to_plot_small = [
  #Quantity(name_nano='BToMuMuPi_mass', name_flat='b_mass', label='b_mass', title='#mu#mu#pi invariant mass [GeV]', nbins=80, bin_min=0.55, bin_max=8),
  Quantity(name_nano='BToMuMuPi_pt', name_flat='b_pt', label='b_pt', title='#mu#mu#pi pT [GeV]', nbins=60, bin_min=0, bin_max=80),
  Quantity(name_nano='BToMuMuPi_hnl_mass', name_flat='hnl_mass', label='hnl_mass', title='#mu#pi invariant mass [GeV]', nbins=80, bin_min=0., bin_max=5.4),
  Quantity(name_nano='BToMuMuPi_trg_mu_pt', name_flat='trgmu_pt', label='trgmu_pt', title='trigger #mu pT [GeV]', nbins=60, bin_min=6, bin_max=20),
  #Quantity(name_nano='fabs(BToMuMuPi_sel_mu_dzS)', name_flat='fabs(trgmu_dzsig)', label='trgmu_dzsig', title='displaced #mu impact parameter significance on z', nbins=60, bin_min=0, bin_max=15),
  #Quantity(name_nano='fabs(BToMuMuPi_sel_mu_dxyS)', name_flat='fabs(trgmu_dxysig)', label='trgmu_dxysig', title='displaced #mu impact parameter significance on xy', nbins=60, bin_min=0, bin_max=15),
  #Quantity(name_nano='BToMuMuPi_fit_pi_pt', name_flat='pi_pt', label='pi_pt', title='displaced #pi pT [GeV]', nbins=50, bin_min=0, bin_max=10),
  #Quantity(name_nano='BToMuMuPi_trgmu_mu_mass', name_flat='trgmu_mu_mass', label='trgmu_mu_mass', title='dimuon invariant mass [GeV]', nbins=40, bin_min=0, bin_max=5),

  #Quantity(name_nano='BToMuMuPi_hnl_cos2D', name_flat='hnl_cos2d', label='hnl_cos2d', title='#mu#pi cos2D', nbins=80, bin_min=0.99, bin_max=1),

  #Quantity(name_nano='fabs(BToMuMuPi_dphi_pi_fit_pi)', name_flat='fabs(deltaphi_pi_fit_pi)', label='deltaphi_pi_fit_pi', title='|#Delta#phi(#pi, fitted #pi)|', nbins=30, bin_min=0, bin_max=1),
  #Quantity(name_nano='fabs(BToMuMuPi_dphi_mu_fit_mu)', name_flat='fabs(deltaphi_mu_fit_mu)', label='deltaphi_mu_fit_mu', title='|#Delta#phi(#mu, fitted #mu)|', nbins=30, bin_min=0, bin_max=0.2),
  #Quantity(name_nano='BToMuMuPi_hnl_cos2D', name_flat='hnl_cos2d', label='hnl_cos2d', title='#mu#pi cos2D', nbins=80, bin_min=0.995, bin_max=1),
  #Quantity(name_nano='BToMuMuPi_fit_pi_pt', name_flat='pi_pt', label='pi_pt', title='displaced #pi pT [GeV]', nbins=150, bin_min=0, bin_max=10),
  #Quantity(name_nano='BToMuMuPi_fit_mu_eta', name_flat='mu_eta', label='mu_eta', title='displaced #mu #eta', nbins=80, bin_min=-2, bin_max=2),
  #Quantity(name_nano='BToMuMuPi_fit_pi_eta', name_flat='pi_eta', label='pi_eta', title='displaced #pi #eta', nbins=80, bin_min=-2, bin_max=2),
  #Quantity(name_nano='BToMuMuPi_sv_prob', name_flat='sv_prob', label='sv_prob', title='displaced vertex probability', nbins=90, bin_min=0, bin_max=0.1),
  #Quantity(name_nano='BToMuMuPi_hnl_charge', name_flat='hnl_charge', label='hnl_charge', title='#mu#pi charge', nbins=7, bin_min=-3, bin_max=3),
  #Quantity(name_nano='BToMuMuPi_trgmu_pi_mass', name_flat='trgmu_pi_mass', label='trgmu_pi_mass', title='trg#mu#pi invariant mass [GeV]', nbins=90, bin_min=0, bin_max=7),
  #Quantity(name_nano='Muon_pfiso03Rel_all[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_pfiso03_rel', label='trgmu_pfiso03_rel', title='trigger #mu relative PF iso03', nbins=90, bin_min=0, bin_max=2),
  #Quantity(name_nano='Muon_pfiso03Rel_all[BToMuMuPi_sel_mu_idx]', name_flat='mu_pfiso03_rel', label='mu_pfiso03_rel', title='displaced #mu relative PF iso03', nbins=90, bin_min=0, bin_max=3),
  ]


quantities_to_plot_all = [
  Quantity(name_nano='BToMuMuPi_sv_lxy', name_flat='sv_lxy', label='sv_lxy_large', title='displaced vertex lxy [cm]', nbins=80, bin_min=0, bin_max=120),
  Quantity(name_nano='BToMuMuPi_sv_lxy', name_flat='sv_lxy', label='sv_lxy', title='displaced vertex lxy [cm]', nbins=80, bin_min=0, bin_max=30),
  Quantity(name_nano='BToMuMuPi_sv_lxy_sig', name_flat='sv_lxysig', label='sv_lxysig_large', title='significance of the displaced vertex lxy', nbins=80, bin_min=0, bin_max=50000),
  Quantity(name_nano='BToMuMuPi_sv_lxy_sig', name_flat='sv_lxysig', label='sv_lxysig', title='significance of the displaced vertex lxy', nbins=80, bin_min=0, bin_max=3000),
  Quantity(name_nano='BToMuMuPi_sv_prob', name_flat='sv_prob', label='sv_prob', title='displaced vertex probability', nbins=70, bin_min=0, bin_max=1.),

  Quantity(name_nano='BToMuMuPi_mass', name_flat='b_mass', label='b_mass', title='#mu#mu#pi invariant mass [GeV]', nbins=80, bin_min=0.55, bin_max=8),
  Quantity(name_nano='BToMuMuPi_pt', name_flat='b_pt', label='b_pt_large', title='#mu#mu#pi pT [GeV]', nbins=60, bin_min=0, bin_max=250),
  Quantity(name_nano='BToMuMuPi_pt', name_flat='b_pt', label='b_pt', title='#mu#mu#pi pT [GeV]', nbins=60, bin_min=0, bin_max=80),
  Quantity(name_nano='BToMuMuPi_eta', name_flat='b_eta', label='b_eta', title='#mu#mu#pi #eta', nbins=50, bin_min=-2, bin_max=2),
  Quantity(name_nano='BToMuMuPi_phi', name_flat='b_phi', label='b_phi', title='#mu#mu#pi #phi', nbins=50, bin_min=-3.2, bin_max=3.2),

  Quantity(name_nano='BToMuMuPi_hnl_mass', name_flat='hnl_mass', label='hnl_mass', title='#mu#pi invariant mass [GeV]', nbins=80, bin_min=0., bin_max=6.5),
  Quantity(name_nano='BToMuMuPi_hnl_pt', name_flat='hnl_pt', label='hnl_pt_large', title='#mu#pi pT [GeV]', nbins=60, bin_min=0, bin_max=250),
  Quantity(name_nano='BToMuMuPi_hnl_pt', name_flat='hnl_pt', label='hnl_pt', title='#mu#pi pT [GeV]', nbins=60, bin_min=0, bin_max=80),
  Quantity(name_nano='BToMuMuPi_hnl_eta', name_flat='hnl_eta', label='hnl_eta', title='#mu#pi #eta', nbins=50, bin_min=-2, bin_max=2),
  Quantity(name_nano='BToMuMuPi_hnl_phi', name_flat='hnl_phi', label='hnl_phi', title='#mu#pi #phi', nbins=50, bin_min=-3.2, bin_max=3.2),
  Quantity(name_nano='BToMuMuPi_hnl_charge', name_flat='hnl_charge', label='hnl_charge', title='#mu#pi charge', nbins=7, bin_min=-3, bin_max=3),
  Quantity(name_nano='BToMuMuPi_hnl_cos2D', name_flat='hnl_cos2d', label='hnl_cos2d', title='#mu#pi cos2D', nbins=60, bin_min=0.995, bin_max=1),
  Quantity(name_nano='BToMuMuPi_hnl_iso03_close', name_flat='hnl_iso03_close', label='hnl_iso03_close', title='#mu#pi iso03', nbins=80, bin_min=0, bin_max=0.1),
  Quantity(name_nano='BToMuMuPi_hnl_iso03_rel_close', name_flat='hnl_iso03_rel_close', label='hnl_iso03_rel_close', title='#mu#pi relative iso03', nbins=80, bin_min=0, bin_max=0.1),
  Quantity(name_nano='BToMuMuPi_hnl_iso04_close', name_flat='hnl_iso04_close', label='hnl_iso04_close', title='#mu#pi iso04', nbins=80, bin_min=0, bin_max=0.1),
  Quantity(name_nano='BToMuMuPi_hnl_iso04_rel_close', name_flat='hnl_iso04_rel_close', label='hnl_iso04_rel_close', title='#mu#pi relative iso04', nbins=80, bin_min=0, bin_max=0.1),

  Quantity(name_nano='BToMuMuPi_trg_mu_pt', name_flat='trgmu_pt', label='trgmu_pt_large', title='trigger #mu pT [GeV]', nbins=60, bin_min=6, bin_max=80),
  Quantity(name_nano='BToMuMuPi_trg_mu_pt', name_flat='trgmu_pt', label='trgmu_pt', title='trigger #mu pT [GeV]', nbins=60, bin_min=6, bin_max=20),
  Quantity(name_nano='BToMuMuPi_trg_mu_eta', name_flat='trgmu_eta', label='trgmu_eta', title='trigger #mu #eta', nbins=50, bin_min=-2, bin_max=2),
  Quantity(name_nano='BToMuMuPi_trg_mu_phi', name_flat='trgmu_phi', label='trgmu_phi', title='trigger #mu #phi', nbins=50, bin_min=-3.2, bin_max=3.2),
  Quantity(name_nano='BToMuMuPi_trg_mu_ip3d', name_flat='trgmu_ip3d', label='trgmu_ip3d', title='trigger #mu 3D impact parameter [cm]', nbins=60, bin_min=0, bin_max=4),
  Quantity(name_nano='BToMuMuPi_trg_mu_sip3d', name_flat='trgmu_ip3dsig', label='trgmu_ip3dsig', title='trigger #mu 3D impact parameter significance', nbins=60, bin_min=0, bin_max=100),
  Quantity(name_nano='fabs(BToMuMuPi_trg_mu_dz)', name_flat='trgmu_dz', label='trgmu_dz', title='trigger #mu impact parameter on z [cm]', nbins=60, bin_min=0, bin_max=15),
  Quantity(name_nano='fabs(BToMuMuPi_trg_mu_dxy)', name_flat='trgmu_dxy', label='trgmu_dxy', title='trigger #mu impact parameter on xy [cm]', nbins=60, bin_min=0, bin_max=0.2),
  Quantity(name_nano='fabs(BToMuMuPi_sel_mu_dzS)', name_flat='fabs(trgmu_dzsig)', label='trgmu_dzsig', title='displaced #mu impact parameter significance on z', nbins=60, bin_min=0, bin_max=15),
  Quantity(name_nano='fabs(BToMuMuPi_sel_mu_dxyS)', name_flat='fabs(trgmu_dxysig)', label='trgmu_dxysig', title='displaced #mu impact parameter significance on xy', nbins=60, bin_min=0, bin_max=200),
  Quantity(name_nano='Muon_pfiso03_all[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_pfiso03', label='trgmu_pfiso03', title='trigger #mu PF iso03', nbins=60, bin_min=0, bin_max=3),
  Quantity(name_nano='Muon_pfiso03Rel_all[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_pfiso03_rel', label='trgmu_pfiso03_rel', title='trigger #mu relative PF iso03', nbins=60, bin_min=0, bin_max=2),
  Quantity(name_nano='BToMuMuPi_trg_mu_iso03_close', name_flat='trgmu_iso03_close', label='trgmu_iso03_close', title='trigger #mu iso03', nbins=60, bin_min=0, bin_max=0.1),
  Quantity(name_nano='BToMuMuPi_trg_mu_iso03_rel_close', name_flat='trgmu_iso03_rel_close', label='trgmu_iso03_rel_close', title='trigger #mu relative iso03', nbins=60, bin_min=0, bin_max=0.1),
  Quantity(name_nano='Muon_pfiso04_all[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_pfiso04', label='trgmu_pfiso04', title='trigger #mu PF iso04', nbins=60, bin_min=0, bin_max=3),
  Quantity(name_nano='Muon_pfiso04Rel_all[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_pfiso04_rel', label='trgmu_pfiso04_rel', title='trigger #mu relative PF iso04', nbins=60, bin_min=0, bin_max=3),
  Quantity(name_nano='BToMuMuPi_trg_mu_iso04_close', name_flat='trgmu_iso04_close', label='trgmu_iso04_close', title='trigger #mu iso04', nbins=60, bin_min=0, bin_max=0.1),
  Quantity(name_nano='BToMuMuPi_trg_mu_iso04_rel_close', name_flat='trgmu_iso04_rel_close', label='trgmu_iso04_rel_close', title='trigger #mu relative iso04', nbins=60, bin_min=0, bin_max=0.1),

  Quantity(name_nano='BToMuMuPi_fit_mu_pt', name_flat='mu_pt', label='mu_pt_large', title='displaced #mu pT [GeV]', nbins=60, bin_min=0, bin_max=200),
  Quantity(name_nano='BToMuMuPi_fit_mu_pt', name_flat='mu_pt', label='mu_pt', title='displaced #mu pT [GeV]', nbins=60, bin_min=0, bin_max=30),
  Quantity(name_nano='BToMuMuPi_fit_mu_eta', name_flat='mu_eta', label='mu_eta', title='displaced #mu #eta', nbins=50, bin_min=-2, bin_max=2),
  Quantity(name_nano='BToMuMuPi_fit_mu_phi', name_flat='mu_phi', label='mu_phi', title='displaced #mu #phi', nbins=50, bin_min=-3.2, bin_max=3.2),
  Quantity(name_nano='BToMuMuPi_sel_mu_ip3d', name_flat='mu_ip3d', label='mu_ip3d', title='displaced #mu 3D impact parameter [cm]', nbins=60, bin_min=0, bin_max=4),
  Quantity(name_nano='BToMuMuPi_sel_mu_sip3d', name_flat='mu_ip3dsig', label='mu_ips3dsig', title='displaced #mu 3D impact parameter significance', nbins=60, bin_min=0, bin_max=100),
  Quantity(name_nano='fabs(BToMuMuPi_sel_mu_dz)', name_flat='fabs(mu_dz)', label='mu_dz', title='displaced #mu impact parameter on z [cm]', nbins=60, bin_min=0, bin_max=2),
  Quantity(name_nano='fabs(BToMuMuPi_sel_mu_dxy)', name_flat='fabs(mu_dxy)', label='mu_dxy', title='displaced #mu impact parameter on xy [cm]', nbins=50, bin_min=0, bin_max=0.3),
  Quantity(name_nano='fabs(BToMuMuPi_sel_mu_dzS)', name_flat='fabs(mu_dzsig)', label='mu_dzsig', title='displaced #mu impact parameter significance on z', nbins=60, bin_min=0, bin_max=15),
  Quantity(name_nano='fabs(BToMuMuPi_sel_mu_dxyS)', name_flat='fabs(mu_dxysig)', label='mu_dxysig', title='displaced #mu impact parameter significance on xy', nbins=60, bin_min=0, bin_max=200),
  Quantity(name_nano='Muon_pfiso03_all[BToMuMuPi_sel_mu_idx]', name_flat='mu_pfiso03', label='mu_pfiso03', title='displaced #mu PF iso03', nbins=60, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_pfiso03Rel_all[BToMuMuPi_sel_mu_idx]', name_flat='mu_pfiso03_rel', label='mu_pfiso03_rel', title='displaced #mu relative PF iso03', nbins=60, bin_min=0, bin_max=3),
  Quantity(name_nano='BToMuMuPi_sel_mu_iso03_close', name_flat='mu_iso03_close', label='mu_iso03_close', title='displaced #mu iso03', nbins=60, bin_min=0, bin_max=0.1),
  Quantity(name_nano='BToMuMuPi_sel_mu_iso03_rel_close', name_flat='mu_iso03_rel_close', label='mu_iso03_rel_close', title='displaced #mu relative iso03', nbins=60, bin_min=0, bin_max=0.1),
  Quantity(name_nano='Muon_pfiso04_all[BToMuMuPi_sel_mu_idx]', name_flat='mu_pfiso04', label='mu_pfiso04', title='displaced #mu PF iso04', nbins=60, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_pfiso04Rel_all[BToMuMuPi_sel_mu_idx]', name_flat='mu_pfiso04_rel', label='mu_pfiso04_rel', title='displaced #mu relative PF iso04', nbins=60, bin_min=0, bin_max=4),
  Quantity(name_nano='BToMuMuPi_sel_mu_iso04_close', name_flat='mu_iso04_close', label='mu_iso04_close', title='displaced #mu iso04', nbins=60, bin_min=0, bin_max=0.1),
  Quantity(name_nano='BToMuMuPi_sel_mu_iso04_rel_close', name_flat='mu_iso04_rel_close', label='mu_iso04_rel_close', title='displaced #mu relative iso04', nbins=60, bin_min=0, bin_max=0.1),

  Quantity(name_nano='BToMuMuPi_fit_pi_pt', name_flat='pi_pt', label='pi_pt_large', title='displaced #pi pT [GeV]', nbins=50, bin_min=0, bin_max=200),
  Quantity(name_nano='BToMuMuPi_fit_pi_pt', name_flat='pi_pt', label='pi_pt', title='displaced #pi pT [GeV]', nbins=50, bin_min=0, bin_max=10),
  Quantity(name_nano='BToMuMuPi_fit_pi_eta', name_flat='pi_eta', label='pi_eta', title='displaced #pi #eta', nbins=50, bin_min=-2, bin_max=2),
  Quantity(name_nano='BToMuMuPi_fit_pi_phi', name_flat='pi_phi', label='pi_phi', title='displaced #pi #phi', nbins=50, bin_min=-3.2, bin_max=3.2),
  Quantity(name_nano='fabs(BToMuMuPi_pi_dz)', name_flat='fabs(pi_dz)', label='pi_dz', title='displaced #pi impact parameter on z [cm]', nbins=60, bin_min=0, bin_max=6),
  Quantity(name_nano='fabs(BToMuMuPi_pi_dxy)', name_flat='fabs(pi_dxy)', label='pi_dxy', title='displaced #pi impact parameter on xy [cm]', nbins=60, bin_min=0, bin_max=4),
  Quantity(name_nano='fabs(BToMuMuPi_pi_dzS)', name_flat='fabs(pi_dzsig)', label='pi_dzsig', title='displaced #pi impact parameter significance on z', nbins=60, bin_min=0, bin_max=500),
  Quantity(name_nano='fabs(BToMuMuPi_pi_dxyS)', name_flat='fabs(pi_dxysig)', label='pi_dxysig', title='displaced #pi impact parameter significance on xy', nbins=60, bin_min=0, bin_max=300),
  Quantity(name_nano='BToMuMuPi_pi_DCASig', name_flat='pi_dcasig', label='pi_dcasig', title='displaced #pi DCA significance on z', nbins=40, bin_min=0, bin_max=80),
  Quantity(name_nano='BToMuMuPi_pi_iso03_close', name_flat='pi_iso03_close', label='pi_iso03_close', title='displaced #pi iso03', nbins=60, bin_min=0, bin_max=0.3),
  Quantity(name_nano='BToMuMuPi_pi_iso03_rel_close', name_flat='pi_iso03_rel_close', label='pi_iso03_rel_close', title='displaced #pi relative iso03', nbins=60, bin_min=0, bin_max=0.3),
  Quantity(name_nano='BToMuMuPi_pi_iso04_close', name_flat='pi_iso04_close', label='pi_iso04_close', title='displaced #pi iso04', nbins=60, bin_min=0, bin_max=0.3),
  Quantity(name_nano='BToMuMuPi_pi_iso04_rel_close', name_flat='pi_iso04_rel_close', label='pi_iso04_rel_close', title='displaced #pi relative iso04', nbins=60, bin_min=0, bin_max=0.3),

  Quantity(name_nano='BToMuMuPi_trgmu_mu_mass', name_flat='trgmu_mu_mass', label='trgmu_mu_mass', title='dimuon invariant mass [GeV]', nbins=40, bin_min=0, bin_max=5),
  Quantity(name_nano='BToMuMuPi_trgmu_mu_pt', name_flat='trgmu_mu_pt', label='trgmu_mu_pt', title='dimuon pT [GeV]', nbins=60, bin_min=0, bin_max=90),
  Quantity(name_nano='BToMuMuPi_trgmu_pi_mass', name_flat='trgmu_pi_mass', label='trgmu_pi_mass', title='trg#mu#pi invariant mass [GeV]', nbins=40, bin_min=0, bin_max=7),
  Quantity(name_nano='BToMuMuPi_trgmu_pi_pt', name_flat='trgmu_pi_pt', label='trgmu_pi_pt', title='trg#mu#pi pT [GeV]', nbins=60, bin_min=0, bin_max=30),

  Quantity(name_nano='BToMuMuPi_dr_mu_pi', name_flat='deltar_mu_pi', label='deltar_mu_pi', title='#Delta R(#mu, #pi)', nbins=30, bin_min=0, bin_max=3.),
  Quantity(name_nano='BToMuMuPi_dr_trgmu_hnl', name_flat='deltar_trgmu_hnl', label='deltar_trgmu_hnl', title='#Delta R(trg#mu, hnl)', nbins=30, bin_min=0, bin_max=0.5),
  Quantity(name_nano='BToMuMuPi_dr_trgmu_mu', name_flat='deltar_trgmu_mu', label='deltar_trgmu_mu', title='#Delta R(trg#mu, #mu)', nbins=30, bin_min=0, bin_max=1.6),
  Quantity(name_nano='BToMuMuPi_dr_trgmu_pi', name_flat='deltar_trgmu_pi', label='deltar_trgmu_pi', title='#Delta R(trg#mu, #pi)', nbins=30, bin_min=0, bin_max=1.6),

  Quantity(name_nano='fabs(BToMuMuPi_deta_mu_pi)', name_flat='fabs(deltaeta_mu_pi)', label='deltaeta_mu_pi', title='|#Delta#eta(#mu, #pi)|', nbins=30, bin_min=0, bin_max=2.),
  Quantity(name_nano='fabs(BToMuMuPi_deta_trgmu_hnl)', name_flat='fabs(deltaeta_trgmu_hnl)', label='deltaeta_trgmu_hnl', title='|#Delta#eta(trg#mu, hnl)|', nbins=30, bin_min=0, bin_max=0.6),
  Quantity(name_nano='fabs(BToMuMuPi_deta_trgmu_mu)', name_flat='fabs(deltaeta_trgmu_mu)', label='deltaeta_trgmu_mu', title='|#Delta#eta(trg#mu, #mu)|', nbins=30, bin_min=0, bin_max=1.),
  Quantity(name_nano='fabs(BToMuMuPi_deta_trgmu_pi)', name_flat='fabs(deltaeta_trgmu_pi)', label='deltaeta_trgmu_pi', title='|#Delta#eta(trg#mu, #pi)| ', nbins=30, bin_min=0, bin_max=1.8),

  Quantity(name_nano='fabs(BToMuMuPi_dphi_mu_pi)', name_flat='fabs(deltaphi_mu_pi)', label='deltaphi_mu_pi', title='|#Delta#phi(#mu, #pi)|', nbins=30, bin_min=0, bin_max=3.2),
  Quantity(name_nano='fabs(BToMuMuPi_dphi_trgmu_hnl)', name_flat='fabs(deltaphi_trgmu_hnl)', label='deltaphi_trgmu_hnl', title='|#Delta#phi(trg#mu, hnl)|', nbins=30, bin_min=0, bin_max=0.5),
  Quantity(name_nano='fabs(BToMuMuPi_dphi_trgmu_mu)', name_flat='fabs(deltaphi_trgmu_mu)', label='deltaphi_trgmu_mu', title='|#Delta#phi(trg#mu, #mu)|', nbins=30, bin_min=0, bin_max=1.),
  Quantity(name_nano='fabs(BToMuMuPi_dphi_trgmu_pi)', name_flat='fabs(deltaphi_trgmu_pi)', label='deltaphi_trgmu_pi', title='|#Delta#phi(trg#mu, #pi)|', nbins=30, bin_min=0, bin_max=3.2),

  Quantity(name_nano='fabs(BToMuMuPi_dpt_pi_fit_pi)', name_flat='fabs(deltapt_pi_fit_pi)', label='deltapt_pi_fit_pi', title='|#Delta pT(#pi, fitted #pi)|', nbins=30, bin_min=0, bin_max=0.02),
  Quantity(name_nano='fabs(BToMuMuPi_dpt_mu_fit_mu)', name_flat='fabs(deltapt_mu_fit_mu)', label='deltapt_mu_fit_mu', title='|#Delta pT(#mu, fitted #mu)|', nbins=30, bin_min=0, bin_max=0.08),
  Quantity(name_nano='fabs(BToMuMuPi_deta_pi_fit_pi)', name_flat='fabs(deltaeta_pi_fit_pi)', label='deltaeta_pi_fit_pi', title='|#Delta#eta(#pi, fitted #pi)|', nbins=30, bin_min=0, bin_max=0.001),
  Quantity(name_nano='fabs(BToMuMuPi_deta_mu_fit_mu)', name_flat='fabs(deltaeta_mu_fit_mu)', label='deltaeta_mu_fit_mu', title='|#Delta#eta(#mu, fitted #mu)|', nbins=30, bin_min=0, bin_max=0.002),
  Quantity(name_nano='fabs(BToMuMuPi_dphi_pi_fit_pi)', name_flat='fabs(deltaphi_pi_fit_pi)', label='deltaphi_pi_fit_pi', title='|#Delta#phi(#pi, fitted #pi)|', nbins=30, bin_min=0, bin_max=0.015),
  Quantity(name_nano='fabs(BToMuMuPi_dphi_mu_fit_mu)', name_flat='fabs(deltaphi_mu_fit_mu)', label='deltaphi_mu_fit_mu', title='|#Delta#phi(#mu, fitted #mu)|', nbins=30, bin_min=0, bin_max=0.01),
  ]


quantities_to_plot_selection = [
  Quantity(name_nano='BToMuMuPi_sv_lxy_sig', name_flat='sv_lxysig', label='sv_lxysig', title='significance of the displaced vertex lxy', nbins=60, bin_min=0, bin_max=350),

  Quantity(name_nano='BToMuMuPi_sv_prob', name_flat='sv_prob', label='sv_prob', title='displaced vertex probability', nbins=90, bin_min=0, bin_max=0.1),

  Quantity(name_nano='BToMuMuPi_mass', name_flat='b_mass', label='b_mass', title='#mu#mu#pi invariant mass [GeV]', nbins=80, bin_min=0.55, bin_max=8),

  Quantity(name_nano='BToMuMuPi_hnl_mass', name_flat='hnl_mass', label='hnl_mass', title='#mu#pi invariant mass [GeV]', nbins=80, bin_min=0.55, bin_max=6.5),
  ##Quantity(name_nano='BToMuMuPi_hnl_pt', name_flat='hnl_pt', label='hnl_pt_large', title='#mu#pi pT [GeV]', nbins=200, bin_min=0, bin_max=250),
  ##Quantity(name_nano='BToMuMuPi_hnl_eta', name_flat='hnl_eta', label='hnl_eta', title='#mu#pi #eta', nbins=80, bin_min=-2, bin_max=2),

  Quantity(name_nano='BToMuMuPi_hnl_cos2D', name_flat='hnl_cos2d', label='hnl_cos2d', title='#mu#pi cos2D', nbins=30, bin_min=0.99, bin_max=1),

  Quantity(name_nano='BToMuMuPi_trg_mu_pt', name_flat='trgmu_pt', label='trgmu_pt', title='trigger #mu pT [GeV]', nbins=60, bin_min=6, bin_max=20),
  Quantity(name_nano='BToMuMuPi_trg_mu_eta', name_flat='trgmu_eta', label='trgmu_eta', title='trigger #mu #eta', nbins=40, bin_min=-2, bin_max=2),

  #Quantity(name_nano='BToMuMuPi_fit_mu_pt', name_flat='mu_pt', label='mu_pt', title='displaced #mu pT [GeV]', nbins=50, bin_min=0, bin_max=30),
  #Quantity(name_nano='BToMuMuPi_fit_mu_eta', name_flat='mu_eta', label='mu_eta', title='displaced #mu #eta', nbins=40, bin_min=-3, bin_max=3),
  #Quantity(name_nano='fabs(BToMuMuPi_sel_mu_dz)', name_flat='fabs(mu_dz)', label='mu_dz', title='displaced #mu impact parameter on z [cm]', nbins=90, bin_min=0, bin_max=0.01),
  #Quantity(name_nano='fabs(BToMuMuPi_sel_mu_dxy)', name_flat='fabs(mu_dxy)', label='mu_dxy', title='displaced #mu impact parameter on xy [cm]', nbins=90, bin_min=0, bin_max=0.01),
  #Quantity(name_nano='fabs(Muon_dzS[BToMuMuPi_sel_mu_idx])', name_flat='fabs(mu_dzsig)', label='mu_dzsig', title='displaced #mu impact parameter significance on z', nbins=60, bin_min=0, bin_max=30),
  #Quantity(name_nano='fabs(Muon_dxyS[BToMuMuPi_sel_mu_idx])', name_flat='fabs(mu_dxysig)', label='mu_dxysig', title='displaced #mu impact parameter significance on xy', nbins=60, bin_min=0, bin_max=30),

  #Quantity(name_nano='BToMuMuPi_fit_pi_pt', name_flat='pi_pt', label='pi_pt', title='displaced #pi pT [GeV]', nbins=50, bin_min=0, bin_max=10),
  #Quantity(name_nano='BToMuMuPi_fit_pi_eta', name_flat='pi_eta', label='pi_eta', title='displaced #pi #eta', nbins=40, bin_min=-3, bin_max=3),
  #Quantity(name_nano='fabs(BToMuMuPi_pi_dz)', name_flat='fabs(pi_dz)', label='pi_dz', title='displaced #pi impact parameter on z [cm]', nbins=40, bin_min=0, bin_max=0.01),
  #Quantity(name_nano='fabs(BToMuMuPi_pi_dxy)', name_flat='fabs(pi_dxy)', label='pi_dxy', title='displaced #pi impact parameter on xy [cm]', nbins=40, bin_min=0, bin_max=0.01),
  #Quantity(name_nano='fabs(BToMuMuPi_pi_dzS)', name_flat='fabs(pi_dzsig)', label='pi_dzsig', title='displaced #pi impact parameter significance on z', nbins=50, bin_min=0, bin_max=30),
  #Quantity(name_nano='fabs(BToMuMuPi_pi_dxyS)', name_flat='fabs(pi_dxysig)', label='pi_dxysig', title='displaced #pi impact parameter significance on xy', nbins=50, bin_min=0, bin_max=30),
  #Quantity(name_nano='BToMuMuPi_pi_DCASig', name_flat='pi_dcasig', label='pi_dcasig', title='displaced #pi DCA significance on z', nbins=50, bin_min=0, bin_max=30),

  #Quantity(name_nano='BToMuMuPi_trgmu_mu_mass', name_flat='trgmu_mu_mass', label='trgmu_mu_mass', title='dimuon invariant mass [GeV]', nbins=90, bin_min=0, bin_max=5),
  #Quantity(name_nano='BToMuMuPi_trgmu_mu_pt', name_flat='trgmu_mu_pt', label='trgmu_mu_pt', title='dimuon pT [GeV]', nbins=150, bin_min=0, bin_max=90),
  #Quantity(name_nano='BToMuMuPi_trgmu_pi_mass', name_flat='trgmu_pi_mass', label='trgmu_pi_mass', title='trg#mu#pi invariant mass [GeV]', nbins=90, bin_min=0, bin_max=7),
  #Quantity(name_nano='BToMuMuPi_trgmu_pi_pt', name_flat='trgmu_pi_pt', label='trgmu_pi_pt', title='trg#mu#pi pT [GeV]', nbins=150, bin_min=0, bin_max=90),

  #Quantity(name_nano='BToMuMuPi_dr_mu_pi', name_flat='deltar_mu_pi', label='deltar_mu_pi', title='#Delta R(#mu, #pi)', nbins=30, bin_min=0, bin_max=3.),
  #Quantity(name_nano='BToMuMuPi_dr_trgmu_hnl', name_flat='deltar_trgmu_hnl', label='deltar_trgmu_hnl', title='#Delta R(trg#mu, hnl)', nbins=30, bin_min=0, bin_max=1),
  #Quantity(name_nano='BToMuMuPi_dr_trgmu_mu', name_flat='deltar_trgmu_mu', label='deltar_trgmu_mu', title='#Delta R(trg#mu, #mu)', nbins=30, bin_min=0, bin_max=1.6),
  #Quantity(name_nano='BToMuMuPi_dr_trgmu_pi', name_flat='deltar_trgmu_pi', label='deltar_trgmu_pi', title='#Delta R(trg#mu, #pi)', nbins=30, bin_min=0, bin_max=1.6),

  #Quantity(name_nano='fabs(BToMuMuPi_deta_mu_pi)', name_flat='fabs(deltaeta_mu_pi)', label='deltaeta_mu_pi', title='|#Delta#eta(#mu, #pi)|', nbins=30, bin_min=0, bin_max=2.),
  #Quantity(name_nano='fabs(BToMuMuPi_deta_trgmu_hnl)', name_flat='fabs(deltaeta_trgmu_hnl)', label='deltaeta_trgmu_hnl', title='|#Delta#eta(trg#mu, hnl)|', nbins=30, bin_min=0, bin_max=0.6),
  #Quantity(name_nano='fabs(BToMuMuPi_deta_trgmu_mu)', name_flat='fabs(deltaeta_trgmu_mu)', label='deltaeta_trgmu_mu', title='|#Delta#eta(trg#mu, #mu)|', nbins=30, bin_min=0, bin_max=1.),
  #Quantity(name_nano='fabs(BToMuMuPi_deta_trgmu_pi)', name_flat='fabs(deltaeta_trgmu_pi)', label='deltaeta_trgmu_pi', title='|#Delta#eta(trg#mu, #pi)| ', nbins=30, bin_min=0, bin_max=1.8),

  #Quantity(name_nano='fabs(BToMuMuPi_dphi_mu_pi)', name_flat='fabs(deltaphi_mu_pi)', label='deltaphi_mu_pi', title='|#Delta#phi(#mu, #pi)|', nbins=30, bin_min=0, bin_max=3.2),
  #Quantity(name_nano='fabs(BToMuMuPi_dphi_trgmu_hnl)', name_flat='fabs(deltaphi_trgmu_hnl)', label='deltaphi_trgmu_hnl', title='|#Delta#phi(trg#mu, hnl)|', nbins=30, bin_min=0, bin_max=0.5),
  #Quantity(name_nano='fabs(BToMuMuPi_dphi_trgmu_mu)', name_flat='fabs(deltaphi_trgmu_mu)', label='deltaphi_trgmu_mu', title='|#Delta#phi(trg#mu, #mu)|', nbins=30, bin_min=0, bin_max=1.),
  #Quantity(name_nano='fabs(BToMuMuPi_dphi_trgmu_pi)', name_flat='fabs(deltaphi_trgmu_pi)', label='deltaphi_trgmu_pi', title='|#Delta#phi(trg#mu, #pi)|', nbins=30, bin_min=0, bin_max=3.2),

  #Quantity(name_nano='BToMuMuPi_dpt_pi_fit_pi', name_flat='deltapt_pi_fit_pi', label='deltapt_pi_fit_pi', title='#Delta pT(#pi, fitted #pi)', nbins=30, bin_min=-15, bin_max=15),
  #Quantity(name_nano='BToMuMuPi_dpt_mu_fit_mu', name_flat='deltapt_mu_fit_mu', label='deltapt_mu_fit_mu', title='#Delta pT(#mu, fitted #mu)', nbins=30, bin_min=-100, bin_max=100),
  #Quantity(name_nano='fabs(BToMuMuPi_deta_pi_fit_pi)', name_flat='fabs(deltaeta_pi_fit_pi)', label='deltaeta_pi_fit_pi', title='|#Delta#eta(#pi, fitted #pi)|', nbins=30, bin_min=0, bin_max=0.1),
  #Quantity(name_nano='fabs(BToMuMuPi_deta_mu_fit_mu)', name_flat='fabs(deltaeta_mu_fit_mu)', label='deltaeta_mu_fit_mu', title='|#Delta#eta(#mu, fitted #mu)|', nbins=30, bin_min=0, bin_max=0.15),
  #Quantity(name_nano='fabs(BToMuMuPi_dphi_pi_fit_pi)', name_flat='fabs(deltaphi_pi_fit_pi)', label='deltaphi_pi_fit_pi', title='|#Delta#phi(#pi, fitted #pi)|', nbins=30, bin_min=0, bin_max=0.1),
  #Quantity(name_nano='fabs(BToMuMuPi_dphi_mu_fit_mu)', name_flat='fabs(deltaphi_mu_fit_mu)', label='deltaphi_mu_fit_mu', title='|#Delta#phi(#mu, fitted #mu)|', nbins=30, bin_min=0, bin_max=0.2),

  #Quantity(name_nano='Muon_pfiso03Rel_all[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_pfiso03_rel', label='trgmu_pfiso03_rel', title='trigger #mu relative PF iso03', nbins=60, bin_min=0, bin_max=2),
  #Quantity(name_nano='Muon_pfiso03Rel_all[BToMuMuPi_sel_mu_idx]', name_flat='mu_pfiso03_rel', label='mu_pfiso03_rel', title='displaced #mu relative PF iso03', nbins=60, bin_min=0, bin_max=3),
  ]


quantities_muonId_study_triggermuon_small = [
  Quantity(name_nano='Muon_isTriggering[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_istriggering', label='trgmu_isTriggering', title='isTriggering', nbins=2, bin_min=0, bin_max=2),
]

quantities_muonId_study_displacedmuon_small = [
  Quantity(name_nano='Muon_isTriggering[BToMuMuPi_sel_mu_idx]', name_flat='mu_istriggering', label='mu_isTriggering', title='isTriggering', nbins=2, bin_min=0, bin_max=2),
  #Quantity(name_nano='Muon_segmentCompatibility[BToMuMuPi_sel_mu_idx]', name_flat='mu_segmentcompatibility', label='mu_segmentCompatibility', title='segmentCompatibility', nbins=50, bin_min=0, bin_max=1.1),
]

quantities_muonId_study_triggermuon = [
  #Quantity(name_nano='BToMuMuPi_trg_mu_pt', name_flat='trgmu_pt', label='trgmu_pt_large1', title='trigger #mu pT [GeV]', nbins=150, bin_min=0, bin_max=200),
  #Quantity(name_nano='Muon_pt[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_pt', label='trgmu_pt_large2', title='trigger #mu pT [GeV]', nbins=150, bin_min=0, bin_max=200),
  #Quantity(name_nano='BToMuMuPi_fit_mu_pt', name_flat='mu_pt', label='selmu_pt_large1', title='displaced #mu pT [GeV]', nbins=150, bin_min=0, bin_max=200),
  #Quantity(name_nano='Muon_pt[BToMuMuPi_sel_mu_idx]', name_flat='trgmu_pt', label='selmu_pt_large2', title='trigger #mu pT [GeV]', nbins=150, bin_min=0, bin_max=200),
  Quantity(name_nano='Muon_isTriggering[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_istriggering', label='trgmu_isTriggering', title='isTriggering', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_looseId[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_looseid', label='trgmu_isLooseMuon', title='isLooseMuon', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_mediumId[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_mediumid', label='trgmu_isMediumMuon', title='isMediumMuon', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_tightId[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_tightid', label='trgmu_isTightMuon', title='isTightMuon', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_softId[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_softid', label='trgmu_isSoftMuon', title='isSoftMuon', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_isPF[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_isPF', label='trgmu_isPF', title='isPF', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_isGlobalMuon[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_isglobalmuon', label='trgmu_isGlobalMuon', title='isGlobalMuon', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_isTrackerMuon[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_istrackermuon', label='trgmu_isTrackerMuon', title='isTrackerMuon', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_isGlobalOrTrackerMuon[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_isglobalortrackermuon', label='trgmu_isGlobalOrTrackerMuon', title='isGlobalOrTrackerMuon', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_isGlobalNotTrackerMuon[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_isglobalnottrackermuon', label='trgmu_isGlobalNotTrackerMuon', title='isGlobalNotTrackerMuon', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_isTrackerNotGlobalMuon[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_istrackernotglobalmuon', label='trgmu_isTrackerNotGlobalMuon', title='isTrackerNotGlobalMuon', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_pfIsoId[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_pfisoid', label='trgmu_pfIsoId', title='pfIsoId', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_tkIsoId[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_trkisoid', label='trgmu_trkIsoId', title='tkIsoId', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_triggerIdLoose[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_triggerlooseid', label='trgmu_triggerIdLoose', title='triggerIdLoose', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_inTimeMuon[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_intimemuon', label='trgmu_inTimeMuon', title='inTimeMuon', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_segmentCompatibility[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_segmentcompatibility', label='trgmu_segmentCompatibility', title='segmentCompatibility', nbins=80, bin_min=0, bin_max=1.1),
  Quantity(name_nano='Muon_validHitFraction[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_validhitfraction', label='trgmu_validHitFraction', title='validHitFraction', nbins=80, bin_min=0, bin_max=1.1),
  Quantity(name_nano='Muon_kinkFinderChi2[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_kinkfinderchi2', label='trgmu_kinkFinderChi2', title='kinkFinderChi2', nbins=150, bin_min=0, bin_max=30),
  Quantity(name_nano='Muon_globalNormalisedChi2[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_globalnormalisedchi2', label='trgmu_globalNormalisedChi2', title='globalNormalisedChi2', nbins=150, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_localPositionChi2[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_localpositionchi2', label='trgmu_localPositionChi2', title='localPositionChi2', nbins=150, bin_min=0, bin_max=8),
  Quantity(name_nano='Muon_caloCompatibility[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_calocompatibility', label='trgmu_caloCompatibility', title='caloCompatibility', nbins=80, bin_min=0, bin_max=1.1),
  Quantity(name_nano='Muon_numberOfValidMuonHits[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_numberofvalidmuonhits', label='trgmu_numberOfValidMuonHits', title='numberOfValidMuonHits', nbins=55, bin_min=0, bin_max=55),
  Quantity(name_nano='Muon_numberOfValidPixelHits[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_numberofvalidpixelhits', label='trgmu_numberOfValidPixelHits', title='numberOfValidPixelHits', nbins=10, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_numberOfTrackerLayers[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_numberoftrackerlayers', label='trgmu_numberOfTrackerLayers', title='numberOfTrackerLayers', nbins=18, bin_min=0, bin_max=18),
  Quantity(name_nano='Muon_numberOfPixelLayers[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_numberofpixellayers', label='trgmu_numberOfPixelLayers', title='numberOfPixelLayers', nbins=6, bin_min=0, bin_max=6),
  Quantity(name_nano='Muon_trackerHighPurityFlag[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_trackerhighpurityflag', label='trgmu_trackerHighPurityFlag', title='trackerHighPurityFlag', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_numberOfStations[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_numberofstations', label='trgmu_numberOfStations', title='numberOfStations', nbins=5, bin_min=0, bin_max=5),
  #Quantity(name_nano='Muon_pfiso03Rel_all[BToMuMuPi_trg_mu_idx]', name_flat='', label='pfiso03Rel_all', title='pfiso03Rel_all', nbins=50, bin_min=0, bin_max=10),
  #Quantity(name_nano='Muon_pfiso03Rel_trk[BToMuMuPi_trg_mu_idx]', name_flat='', label='pfiso03Rel_trk', title='pfiso03Rel_trk', nbins=50, bin_min=0, bin_max=10),
  #Quantity(name_nano='Muon_pfiso03Rel_ch[BToMuMuPi_trg_mu_idx]', name_flat='', label='pfiso03Rel_ch', title='pfiso03Rel_ch', nbins=50, bin_min=0, bin_max=10),
  #Quantity(name_nano='Muon_pfiso03Rel_n[BToMuMuPi_trg_mu_idx]', name_flat='', label='pfiso03Rel_n', title='pfiso03Rel_n', nbins=50, bin_min=0, bin_max=10),
  #Quantity(name_nano='Muon_pfiso03Rel_pho[BToMuMuPi_trg_mu_idx]', name_flat='', label='pfiso03Rel_pho', title='pfiso03Rel_pho', nbins=50, bin_min=0, bin_max=10),
  #Quantity(name_nano='Muon_pfiso03Rel_pu[BToMuMuPi_trg_mu_idx]', name_flat='', label='pfiso03Rel_pu', title='pfiso03Rel_pu', nbins=50, bin_min=0, bin_max=10),
  #Quantity(name_nano='Muon_pfiso04Rel_all[BToMuMuPi_trg_mu_idx]', name_flat='', label='pfiso04Rel_all', title='pfiso04Rel_all', nbins=50, bin_min=0, bin_max=10),
  #Quantity(name_nano='Muon_pfiso05Rel_trk[BToMuMuPi_trg_mu_idx]', name_flat='', label='pfiso05Rel_trk', title='pfiso05Rel_trk', nbins=50, bin_min=0, bin_max=10),
  #Quantity(name_nano='Muon_pfiso04Rel_ch[BToMuMuPi_trg_mu_idx]', name_flat='', label='pfiso04Rel_ch', title='pfiso04Rel_ch', nbins=50, bin_min=0, bin_max=10),
  #Quantity(name_nano='Muon_pfiso04Rel_n[BToMuMuPi_trg_mu_idx]', name_flat='', label='pfiso04Rel_n', title='pfiso04Rel_n', nbins=50, bin_min=0, bin_max=10),
  #Quantity(name_nano='Muon_pfiso04Rel_pho[BToMuMuPi_trg_mu_idx]', name_flat='', label='pfiso04Rel_pho', title='pfiso04Rel_pho', nbins=50, bin_min=0, bin_max=10),
  #Quantity(name_nano='Muon_pfiso04Rel_pu[BToMuMuPi_trg_mu_idx]', name_flat='', label='pfiso04Rel_pu', title='pfiso04Rel_pu', nbins=50, bin_min=0, bin_max=10),
]

quantities_muonId_study_displacedmuon = [
  ##Quantity(name_nano='BToMuMuPi_trg_mu_pt', name_flat='trgmu_pt', label='trgmu_pt_large1', title='trigger #mu pT [GeV]', nbins=150, bin_min=0, bin_max=200),
  ##Quantity(name_nano='Muon_pt[BToMuMuPi_trg_mu_idx]', name_flat='trgmu_pt', label='trgmu_pt_large2', title='trigger #mu pT [GeV]', nbins=150, bin_min=0, bin_max=200),
  ##Quantity(name_nano='BToMuMuPi_fit_mu_pt', name_flat='mu_pt', label='selmu_pt_large1', title='displaced #mu pT [GeV]', nbins=150, bin_min=0, bin_max=200),
  ##Quantity(name_nano='Muon_pt[BToMuMuPi_sel_mu_idx]', name_flat='trgmu_pt', label='selmu_pt_large2', title='trigger #mu pT [GeV]', nbins=150, bin_min=0, bin_max=200),
  Quantity(name_nano='Muon_isTriggering[BToMuMuPi_sel_mu_idx]', name_flat='mu_istriggering', label='mu_isTriggering', title='isTriggering', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_looseId[BToMuMuPi_sel_mu_idx]', name_flat='mu_looseid', label='mu_isLooseMuon', title='isLooseMuon', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_mediumId[BToMuMuPi_sel_mu_idx]', name_flat='mu_mediumid', label='mu_isMediumMuon', title='isMediumMuon', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_tightId[BToMuMuPi_sel_mu_idx]', name_flat='mu_tightid', label='mu_isTightMuon', title='isTightMuon', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_softId[BToMuMuPi_sel_mu_idx]', name_flat='mu_softid', label='mu_isSoftMuon', title='isSoftMuon', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_isPF[BToMuMuPi_sel_mu_idx]', name_flat='mu_isPF', label='mu_isPF', title='isPF', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_isGlobalMuon[BToMuMuPi_sel_mu_idx]', name_flat='mu_isglobalmuon', label='mu_isGlobalMuon', title='isGlobalMuon', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_isTrackerMuon[BToMuMuPi_sel_mu_idx]', name_flat='mu_istrackermuon', label='mu_isTrackerMuon', title='isTrackerMuon', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_isGlobalOrTrackerMuon[BToMuMuPi_sel_mu_idx]', name_flat='mu_isglobalortrackermuon', label='mu_isGlobalOrTrackerMuon', title='isGlobalOrTrackerMuon', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_isGlobalNotTrackerMuon[BToMuMuPi_sel_mu_idx]', name_flat='mu_isglobalnottrackermuon', label='mu_isGlobalNotTrackerMuon', title='isGlobalNotTrackerMuon', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_isTrackerNotGlobalMuon[BToMuMuPi_sel_mu_idx]', name_flat='mu_istrackernotglobalmuon', label='mu_isTrackerNotGlobalMuon', title='isTrackerNotGlobalMuon', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_pfIsoId[BToMuMuPi_sel_mu_idx]', name_flat='mu_pfisoid', label='mu_pfIsoId', title='pfIsoId', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_tkIsoId[BToMuMuPi_sel_mu_idx]', name_flat='mu_trkisoid', label='mu_tkIsoId', title='tkIsoId', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_triggerIdLoose[BToMuMuPi_sel_mu_idx]', name_flat='mu_triggerlooseid', label='mu_triggerIdLoose', title='triggerIdLoose', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_inTimeMuon[BToMuMuPi_sel_mu_idx]', name_flat='mu_intimemuon', label='mu_inTimeMuon', title='inTimeMuon', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_segmentCompatibility[BToMuMuPi_sel_mu_idx]', name_flat='mu_segmentcompatibility', label='mu_segmentCompatibility', title='segmentCompatibility', nbins=50, bin_min=0, bin_max=1.1),
  Quantity(name_nano='Muon_validHitFraction[BToMuMuPi_sel_mu_idx]', name_flat='mu_validhitfraction', label='mu_validHitFraction', title='validHitFraction', nbins=50, bin_min=0.5, bin_max=1.01),
  Quantity(name_nano='Muon_kinkFinderChi2[BToMuMuPi_sel_mu_idx]', name_flat='mu_kinkfinderchi2', label='mu_kinkFinderChi2', title='kinkFinderChi2', nbins=50, bin_min=0, bin_max=30),
  Quantity(name_nano='Muon_globalNormalisedChi2[BToMuMuPi_sel_mu_idx]', name_flat='mu_globalnormalisedchi2', label='mu_globalNormalisedChi2', title='globalNormalisedChi2', nbins=50, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_localPositionChi2[BToMuMuPi_sel_mu_idx]', name_flat='mu_localpositionchi2', label='mu_localPositionChi2', title='localPositionChi2', nbins=50, bin_min=0, bin_max=8),
  Quantity(name_nano='Muon_caloCompatibility[BToMuMuPi_sel_mu_idx]', name_flat='mu_calocompatibility', label='mu_caloCompatibility', title='caloCompatibility', nbins=50, bin_min=0, bin_max=1.1),
  Quantity(name_nano='Muon_numberOfValidMuonHits[BToMuMuPi_sel_mu_idx]', name_flat='mu_numberofvalidmuonhits', label='mu_numberOfValidMuonHits', title='numberOfValidMuonHits', nbins=55, bin_min=0, bin_max=55),
  Quantity(name_nano='Muon_numberOfValidPixelHits[BToMuMuPi_sel_mu_idx]', name_flat='mu_numberofvalidpixelhits', label='mu_numberOfValidPixelHits', title='numberOfValidPixelHits', nbins=10, bin_min=0, bin_max=10),
  Quantity(name_nano='Muon_numberOfTrackerLayers[BToMuMuPi_sel_mu_idx]', name_flat='mu_numberoftrackerlayers', label='mu_numberOfTrackerLayers', title='numberOfTrackerLayers', nbins=18, bin_min=0, bin_max=18),
  Quantity(name_nano='Muon_numberOfPixelLayers[BToMuMuPi_sel_mu_idx]', name_flat='mu_numberofpixellayers', label='mu_numberOfPixelLayers', title='numberOfPixelLayers', nbins=6, bin_min=0, bin_max=6),
  Quantity(name_nano='Muon_trackerHighPurityFlag[BToMuMuPi_sel_mu_idx]', name_flat='mu_trackerhighpurityflag', label='mu_trackerHighPurityFlag', title='trackerHighPurityFlag', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='Muon_numberOfStations[BToMuMuPi_sel_mu_idx]', name_flat='mu_numberofstations', label='mu_numberOfStations', title='numberOfStations', nbins=5, bin_min=0, bin_max=5),
  #Quantity(name_nano='Muon_pfiso03Rel_all[BToMuMuPi_sel_mu_idx]', name_flat='', label='pfiso03Rel_all', title='pfiso03Rel_all', nbins=50, bin_min=0, bin_max=10),
  #Quantity(name_nano='Muon_pfiso03Rel_trk[BToMuMuPi_sel_mu_idx]', name_flat='', label='pfiso03Rel_trk', title='pfiso03Rel_trk', nbins=50, bin_min=0, bin_max=10),
  #Quantity(name_nano='Muon_pfiso03Rel_ch[BToMuMuPi_sel_mu_idx]', name_flat='', label='pfiso03Rel_ch', title='pfiso03Rel_ch', nbins=50, bin_min=0, bin_max=10),
  #Quantity(name_nano='Muon_pfiso03Rel_n[BToMuMuPi_sel_mu_idx]', name_flat='', label='pfiso03Rel_n', title='pfiso03Rel_n', nbins=50, bin_min=0, bin_max=10),
  #Quantity(name_nano='Muon_pfiso03Rel_pho[BToMuMuPi_sel_mu_idx]', name_flat='', label='pfiso03Rel_pho', title='pfiso03Rel_pho', nbins=50, bin_min=0, bin_max=10),
  #Quantity(name_nano='Muon_pfiso03Rel_pu[BToMuMuPi_sel_mu_idx]', name_flat='', label='pfiso03Rel_pu', title='pfiso03Rel_pu', nbins=50, bin_min=0, bin_max=10),
  #Quantity(name_nano='Muon_pfiso04Rel_all[BToMuMuPi_sel_mu_idx]', name_flat='', label='pfiso04Rel_all', title='pfiso04Rel_all', nbins=50, bin_min=0, bin_max=10),
  #Quantity(name_nano='Muon_pfiso05Rel_trk[BToMuMuPi_sel_mu_idx]', name_flat='', label='pfiso05Rel_trk', title='pfiso05Rel_trk', nbins=50, bin_min=0, bin_max=10),
  #Quantity(name_nano='Muon_pfiso04Rel_ch[BToMuMuPi_sel_mu_idx]', name_flat='', label='pfiso04Rel_ch', title='pfiso04Rel_ch', nbins=50, bin_min=0, bin_max=10),
  #Quantity(name_nano='Muon_pfiso04Rel_n[BToMuMuPi_sel_mu_idx]', name_flat='', label='pfiso04Rel_n', title='pfiso04Rel_n', nbins=50, bin_min=0, bin_max=10),
  #Quantity(name_nano='Muon_pfiso04Rel_pho[BToMuMuPi_sel_mu_idx]', name_flat='', label='pfiso04Rel_pho', title='pfiso04Rel_pho', nbins=50, bin_min=0, bin_max=10),
  #Quantity(name_nano='Muon_pfiso04Rel_pu[BToMuMuPi_sel_mu_idx]', name_flat='', label='pfiso04Rel_pu', title='pfiso04Rel_pu', nbins=50, bin_min=0, bin_max=10),
]

quantities_trackId = [
  Quantity(name_nano='ProbeTracks_chi2[BToMuMuPi_pi_idx]', name_flat='', label='pi_chi2', title='pi #chi^{2}', nbins=100, bin_min=0, bin_max=30),
  Quantity(name_nano='ProbeTracks_ndof[BToMuMuPi_pi_idx]', name_flat='', label='pi_ndof', title='pi ndof', nbins=40, bin_min=0, bin_max=40),
  Quantity(name_nano='ProbeTracks_normalisedChi2[BToMuMuPi_pi_idx]', name_flat='', label='pi_normalisedChi2', title='pi #chi^{2}/ndof', nbins=30, bin_min=0, bin_max=5),
  Quantity(name_nano='ProbeTracks_numberOfValidHits[BToMuMuPi_pi_idx]', name_flat='', label='pi_numberOfValidHits', title='pi numberOfValidHits', nbins=35, bin_min=0, bin_max=35),
  Quantity(name_nano='ProbeTracks_chi2[BToMuMuPi_pi_idx]', name_flat='', label='pi_chi2', title='pi #chi^{2}', nbins=100, bin_min=0, bin_max=30),
  Quantity(name_nano='ProbeTracks_numberOfLostHits[BToMuMuPi_pi_idx]', name_flat='', label='pi_numberOfLostHits', title='pi numberOfLostHits', nbins=3, bin_min=0, bin_max=3),
  Quantity(name_nano='ProbeTracks_numberOfValidPixelHit[BToMuMuPi_pi_idx]', name_flat='', label='pi_numberOfValidPixelHit', title='pi numberOfValidPixelHit', nbins=10, bin_min=0, bin_max=10),
  Quantity(name_nano='ProbeTracks_numberOfTrackerLayers[BToMuMuPi_pi_idx]', name_flat='', label='pi_numberOfTrackerLayers', title='pi numberOfTrackerLayers', nbins=21, bin_min=0, bin_max=21),
  Quantity(name_nano='ProbeTracks_numberOfPixelLayers[BToMuMuPi_pi_idx]', name_flat='', label='pi_numberOfPixelLayers', title='pi numberOfPixelLayers', nbins=6, bin_min=0, bin_max=6),
  Quantity(name_nano='ProbeTracks_qualityIndex[BToMuMuPi_pi_idx]', name_flat='', label='pi_qualityIndex', title='pi qualityIndex', nbins=6, bin_min=0, bin_max=6),
  Quantity(name_nano='ProbeTracks_highPurityFlag[BToMuMuPi_pi_idx]', name_flat='', label='pi_highPurityFlag', title='pi highPurityFlag', nbins=2, bin_min=0, bin_max=2),
  Quantity(name_nano='ProbeTracks_validFraction[BToMuMuPi_pi_idx]', name_flat='', label='pi_validFraction', title='pi validFraction', nbins=35, bin_min=0.6, bin_max=1),
]

quantities_tag_and_probe = [
  Quantity(name_nano='JPsiToMuMu_pt', name_flat='pt', label='pt', title='#mu#mu pT [GeV]', nbins=100, bin_min=0, bin_max=50),
  Quantity(name_nano='JPsiToMuMu_eta', name_flat='eta', label='eta', title='#mu#mu |#eta|', nbins=60, bin_min=0, bin_max=2),
  Quantity(name_nano='JPsiToMuMu_phi', name_flat='phi', label='phi', title='#mu#mu #phi', nbins=60, bin_min=-3.2, bin_max=3.2),
  Quantity(name_nano='JPsiToMuMu_mass', name_flat='mass', label='mass', title='#mu#mu mass [GeV]', nbins=60, bin_min=2.9, bin_max=3.3),
  Quantity(name_nano='JPsiToMuMu_lxy', name_flat='lxy', label='lxy', title='#mu#mu l_{xy} [cm]', nbins=60, bin_min=0, bin_max=3),
  Quantity(name_nano='JPsiToMuMu_lxy_sig', name_flat='lxy_sig', label='lxy_sig', title='#mu#mu l_{xy} significance', nbins=60, bin_min=0, bin_max=200),
  Quantity(name_nano='JPsiToMuMu_lep1_pt', name_flat='tag_pt', label='tag_pt', title='tag #mu pT [GeV]', nbins=100, bin_min=0, bin_max=50),
  Quantity(name_nano='JPsiToMuMu_lep1_eta', name_flat='tag_eta', label='tag_eta', title='tag #mu |#eta|', nbins=60, bin_min=0, bin_max=2),
  Quantity(name_nano='JPsiToMuMu_lep1_phi', name_flat='tag_phi', label='tag_phi', title='tag #mu #phi', nbins=60, bin_min=-3.2, bin_max=3.2),
  Quantity(name_nano='JPsiToMuMu_lep1_dxy', name_flat='tag_dxy', label='tag_dxy', title='tag #mu |d_{xy}| [cm]', nbins=60, bin_min=0, bin_max=0.15),
  Quantity(name_nano='JPsiToMuMu_lep1_dz', name_flat='tag_dz', label='tag_dz', title='tag #mu |d_{z}| [cm]', nbins=60, bin_min=0, bin_max=0.5),
  Quantity(name_nano='JPsiToMuMu_lep1_dxy_sig', name_flat='tag_dxy_sig', label='tag_dxy_sig', title='tag #mu |d_{xy}| significance', nbins=90, bin_min=0, bin_max=60),
  Quantity(name_nano='JPsiToMuMu_lep1_dz_sig', name_flat='tag_dz_sig', label='tag_dz_sig', title='tag #mu |d_{z}| significance', nbins=90, bin_min=0, bin_max=100),
  Quantity(name_nano='JPsiToMuMu_lep2_pt', name_flat='probe_pt', label='probe_pt', title='probe #mu pT [GeV]', nbins=100, bin_min=0, bin_max=50),
  Quantity(name_nano='JPsiToMuMu_lep2_eta', name_flat='probe_eta', label='probe_eta', title='probe #mu |#eta|', nbins=60, bin_min=0, bin_max=2),
  Quantity(name_nano='JPsiToMuMu_lep2_phi', name_flat='probe_phi', label='probe_phi', title='probe #mu #phi', nbins=60, bin_min=-3.2, bin_max=3.2),
  Quantity(name_nano='JPsiToMuMu_lep2_dxy', name_flat='probe_dxy', label='probe_dxy', title='probe #mu |d_{xy}| [cm]', nbins=60, bin_min=0, bin_max=0.15),
  Quantity(name_nano='JPsiToMuMu_lep2_dz', name_flat='probe_dz', label='probe_dz', title='probe #mu |d_{z}| [cm]', nbins=60, bin_min=0, bin_max=0.5),
  Quantity(name_nano='JPsiToMuMu_lep2_dxy_sig', name_flat='probe_dxy_sig', label='probe_dxy_sig', title='probe #mu |d_{xy}| significance', nbins=90, bin_min=0, bin_max=60),
  Quantity(name_nano='JPsiToMuMu_lep2_dz_sig', name_flat='probe_dz_sig', label='probe_dz_sig', title='probe #mu |d_{z}| significance', nbins=90, bin_min=0, bin_max=100),

]
